## numero 1
FROM golang:1.26-alpine AS builder
WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o server .

## numero 2
FROM alpine:latest
WORKDIR /app

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
COPY --from=builder /app/server .

USER appuser

EXPOSE 9090

CMD ["./server"]